sudo: required

language: node_js

node_js:
  - 10

env:
  matrix:
    - MONGODB=3.2

services:
  - docker

before_script:
  - docker run -d -p 27017:27017 mongo:$MONGODB
  - docker ps -a
  - npm install coveralls -g

script:
  - TEST_DB_URL=mongodb://localhost:27017/rick_and_morty_test travis_retry yarn test

after_success:
  - npm run coveralls